/**
 * fleet.spec.ts — e2e coverage for the Phase 8.6 Pattern A
 * Fleet route (/app/fleet).
 *
 * What this asserts (the must-haves for "the fleet skeleton works
 * end-to-end"):
 *   - GET /app/fleet returns 2xx (route resolves, auth works, the
 *     TanStack dev server renders the workspace)
 *   - The Armenian H2 "Ավտոպարկ" is visible (matches the legacy
 *     H2 the route renders verbatim so the migration e2e is
 *     stable)
 *   - The English subtitle "Fleet" is present (bilingual header)
 *   - The 7 tab buttons render (vehicles, drivers, trips, fuel,
 *     repairs, tires, coldchain) and the default active tab is
 *     Vehicles
 *   - Clicking each tab button switches the visible panel
 *   - The Vehicles tab POSTs to /api/fleet/vehicles with the
 *     {plate, make, model, year, kind, idempotencyKey} envelope
 *   - The Drivers tab POSTs to /api/fleet/drivers with the
 *     {fullName, phone, licenseNumber, idempotencyKey} envelope
 *   - The Trips tab POSTs to /api/fleet/trips and the resulting
 *     row's "departed" button PATCHes /api/fleet/trips/:id/status
 *   - The Fuel tab POSTs to /api/fleet/fuel-logs and the
 *     efficiency table renders the {vehicleId, lPer100km} rows
 *   - The Repairs tab POSTs to /api/fleet/repairs and the
 *     backlog table renders the {vehicleId, kind, overdueDays}
 *     rows
 *   - The Tires tab POSTs to /api/fleet/tires/install
 *   - The ColdChain tab GETs /api/fleet/vehicles/:id/cold-chain
 *     -compliance?category=… and the breaches table renders
 *   - The back link points to /app (the Today hub)
 *   - The 403 access-denied card is NOT rendered for a default
 *     authenticated user (mirrors procurement + assets — the
 *     route is permissive today and the gate is server-side)
 *
 * Mocking strategy: the modern route uses Zod-validated JSON
 * over the 7 POST/PATCH endpoints and 3 GET endpoints (compliance
 * + 2 analytics). The route.intercept handlers below reply with
 * the stable shapes the route's Zod schemas expect (`ok: true` +
 * the typed payload). The 7 list GETs the parent's on-mount
 * `Promise.all` fires (vehicles, drivers, trips, fuel-logs,
 * repairs, tires, cold-chain) also pass through to the live
 * server — by the time my branch lands on main (last in merge
 * order), the fl-server branch will have added the 7 missing
 * list GETs, so the e2e will exercise the real list endpoints
 * too.
 *
 * Why a dedicated spec: this is the Phase 8.6 fleet migration
 * e2e, separate from the broader apps smoke loop. The contract
 * parity is locked at the server tier by the new
 * `test/fleet-list-endpoints.test.js` (worker 1) + the existing
 * fleet analytics + compliance tests; this spec confirms the
 * modern route wires the same shape into the UI. The e2e +
 * this worktree's `git rm web/src/fleet.jsx` together verify
 * the legacy drop is complete: no other file in web/,
 * web-modern/, server/, or test/ references the legacy
 * `FleetPanel` symbol or `web/src/fleet.jsx` after this commit.
 *
 * NOT asserted here (deferred to 8.6b–8.6f sub-plans):
 *   - The TanStack-Query refetch chain after a successful POST
 *     (covered at the unit tier; out of scope for browser e2e)
 *   - The trip status state machine transitions for "arrived"
 *     and "cancelled" (covered at the unit tier by the
 *     co-located vitest spec)
 *   - The `fleetTabFromHash` URL-hash → tab wiring
 *     (covered at the unit tier)
 *   - The cold-chain analytics rollup beyond the breach list
 *     (worstTempC + sustainedMinutes rendering is the route's
 *     job; the unit test verifies the helper)
 */
import { test, expect, type Route, type Request } from "@playwright/test";
import { authedPage, waitForHydration } from "./_helpers";

/* ────────── mock data (matches the Zod schemas) ────────── */

const VEHICLE_ID = "veh-e2e-001";
const DRIVER_ID = "drv-e2e-002";
const TRIP_ID = "trip-e2e-003";
const FUEL_ID = "fuel-e2e-004";
const REPAIR_ID = "rep-e2e-005";
const TIRE_ID = "tire-e2e-006";

/** The seven fleet tabs in the order the route renders them. */
const FLEET_TABS = [
  "vehicles",
  "drivers",
  "trips",
  "fuel",
  "repairs",
  "tires",
  "coldchain",
] as const;

/* ────────── API mocks ────────── */

/** Match a request pathname to a string literal. We use the URL
 *  parser to avoid string-prefix false positives (e.g. the
 *  "/:id/status" suffix on /api/fleet/trips/:id/status must
 *  not match a hypothetical /api/fleet/trips/:id/status-foo
 *  endpoint). */
function requestMatchesPath(req: Request, path: string): boolean {
  const url = new URL(req.url());
  return url.pathname === path;
}

/** Match a PATCH to the trip status endpoint with a regex
 *  (the :id segment is generated by the server, so we can't
 *  match it literally). */
function requestMatchesTripStatusPatch(req: Request): boolean {
  if (req.method() !== "PATCH") return false;
  const url = new URL(req.url());
  return /^\/api\/fleet\/trips\/[^/]+\/status$/.test(url.pathname);
}

/** Match the cold-chain-compliance GET with a query string.
 *  The route uses a `<select>` for category, so the value is
 *  bounded; we just match the path + a "category=" query
 *  presence. */
function requestMatchesColdChainCompliance(req: Request): boolean {
  if (req.method() !== "GET") return false;
  const url = new URL(req.url());
  if (!/^\/api\/fleet\/vehicles\/[^/]+\/cold-chain-compliance$/.test(url.pathname)) {
    return false;
  }
  return url.searchParams.has("category");
}

/** Route the seven fleet POST/PATCH + 3 special GET endpoints
 *  to stable mock payloads. The seven list GETs (vehicles,
 *  drivers, trips, fuel-logs, repairs, tires, cold-chain) and
 *  the two analytics GETs (fuel-efficiency, maintenance-
 *  backlog) pass through to the live backend unchanged — by
 *  the time my branch lands on main (last in merge order),
 *  worker 1 (fl-server) will have added the 7 missing list
 *  GETs to server/app.js, so the e2e will exercise the real
 *  list endpoints too. */
function installFleetApiMocks(route: Route): void {
  if (requestMatchesPath(route.request(), "/api/fleet/vehicles")) {
    if (route.request().method() === "POST") {
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({ ok: true, vehicle: { id: VEHICLE_ID } }),
      });
      return;
    }
  }
  if (requestMatchesPath(route.request(), "/api/fleet/drivers")) {
    if (route.request().method() === "POST") {
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({ ok: true, driver: { id: DRIVER_ID } }),
      });
      return;
    }
  }
  if (requestMatchesPath(route.request(), "/api/fleet/trips")) {
    if (route.request().method() === "POST") {
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({ ok: true, trip: { id: TRIP_ID } }),
      });
      return;
    }
  }
  if (requestMatchesTripStatusPatch(route.request())) {
    route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({ ok: true, trip: { id: TRIP_ID, status: "in_transit" } }),
    });
    return;
  }
  if (requestMatchesPath(route.request(), "/api/fleet/fuel-logs")) {
    if (route.request().method() === "POST") {
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({ ok: true, log: { id: FUEL_ID } }),
      });
      return;
    }
  }
  if (requestMatchesPath(route.request(), "/api/fleet/repairs")) {
    if (route.request().method() === "POST") {
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({ ok: true, repair: { id: REPAIR_ID } }),
      });
      return;
    }
  }
  if (requestMatchesPath(route.request(), "/api/fleet/tires/install")) {
    route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({ ok: true, tire: { id: TIRE_ID } }),
    });
    return;
  }
  if (requestMatchesColdChainCompliance(route.request())) {
    route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({
        ok: true,
        category: "dairy",
        report: {
          worstTempC: 6.4,
          sustainedMinutes: 28,
          breaches: [
            { startedAt: "2026-06-12T08:14:00Z", endedAt: "2026-06-12T08:42:00Z", minutes: 28 },
          ],
        },
      }),
    });
    return;
  }
  // Anything else under /api/fleet passes through to the live
  // backend (so the e2e can still observe a missing-route
  // regression if the Fastify handler disappears).
  route.continue();
}

/* ────────── page shell + tab switch ────────── */

test.describe("Fleet — Phase 8.6 Pattern A skeleton", () => {
  test("loads, renders the H2 + 7 tabs, defaults to Vehicles, and points back to /app", async ({
    browser,
    request,
    page,
  }) => {
    await page.route("**/api/fleet/**", installFleetApiMocks);

    const ctx = await authedPage(browser, request);
    try {
      const response = await ctx.page.goto("/app/fleet");
      expect(
        response,
        `expected /app/fleet to respond (got ${response?.status()})`,
      ).not.toBeNull();
      expect([200, 304]).toContain(response!.status());

      await waitForHydration(ctx.page);

      // H2 — the Armenian title. The route renders "Ավտոպարկ"
      // (lit. "Vehicle Park" / "Fleet", the legacy H2 verbatim)
      // so the e2e is stable across the migration.
      const panel = ctx.page.getByTestId("fleet-panel");
      await expect(panel).toBeVisible();
      const title = ctx.page.getByTestId("fleet-title");
      await expect(title).toBeVisible();
      expect(title.textContent ?? "").toMatch(/Ավտոպարկ/);

      // English subtitle (bilingual header — Armenian H2 + English <p>).
      const subtitle = ctx.page.getByTestId("fleet-subtitle");
      await expect(subtitle).toBeVisible();
      expect(subtitle.textContent ?? "").toContain("Fleet");

      // 7 tab buttons render in route-local order.
      for (const t of FLEET_TABS) {
        const btn = ctx.page.getByTestId(`fleet-tab-${t}`);
        await expect(btn).toBeVisible();
      }

      // Default tab is Vehicles — the route's initial state.
      const vehicles = ctx.page.getByTestId("fleet-tab-vehicles");
      expect(await vehicles.getAttribute("data-active")).toBe("true");
      await expect(
        ctx.page.getByTestId("fleet-vehicles-form"),
      ).toBeVisible();

      // Click each tab — the matching form appears, the
      // previously-active form unmounts.
      for (const t of FLEET_TABS) {
        await ctx.page.getByTestId(`fleet-tab-${t}`).click();
        expect(
          await ctx.page.getByTestId(`fleet-tab-${t}`).getAttribute("data-active"),
        ).toBe("true");
        await expect(ctx.page.getByTestId(`fleet-${t}-form`)).toBeVisible();
      }

      // Back link — every Pattern A app has a ChevronLeft link
      // pointing to /app (the Today hub). The legacy module
      // used "← back to Today" so the visible label is the
      // most stable assertion.
      const back = ctx.page.getByRole("link", { name: /back to Today/i });
      await expect(back).toBeVisible();
      await expect(back).toHaveAttribute("href", "/app");
    } finally {
      await ctx.page.context().close();
    }
  });
});

/* ────────── Vehicles POST ────────── */

test.describe("Fleet — Vehicles POST", () => {
  test("filling the form + clicking submit POSTs to /api/fleet/vehicles with the idempotency key", async ({
    browser,
    request,
    page,
  }) => {
    interface VehiclePostBody {
      plate: string;
      make: string;
      model: string;
      year?: number;
      kind?: string;
      idempotencyKey: string;
    }
    let postBody: VehiclePostBody | null = null;
    await page.route("**/api/fleet/**", async (route) => {
      if (
        requestMatchesPath(route.request(), "/api/fleet/vehicles") &&
        route.request().method() === "POST"
      ) {
        try {
          const raw = JSON.parse(route.request().postData() ?? "{}") as Partial<VehiclePostBody>;
          postBody = {
            plate: String(raw.plate ?? ""),
            make: String(raw.make ?? ""),
            model: String(raw.model ?? ""),
            year: typeof raw.year === "number" ? raw.year : undefined,
            kind: typeof raw.kind === "string" ? raw.kind : undefined,
            idempotencyKey: String(raw.idempotencyKey ?? ""),
          };
        } catch {
          postBody = null;
        }
        route.fulfill({
          status: 200,
          contentType: "application/json",
          body: JSON.stringify({ ok: true, vehicle: { id: VEHICLE_ID } }),
        });
        return;
      }
      installFleetApiMocks(route);
    });

    const ctx = await authedPage(browser, request);
    try {
      await ctx.page.goto("/app/fleet");
      await waitForHydration(ctx.page);

      // The Vehicles tab is the default — no need to click it.
      await expect(
        ctx.page.getByTestId("fleet-vehicles-form"),
      ).toBeVisible();

      // Fill the form: plate, make, model, year, kind.
      await ctx.page.getByTestId("fleet-vehicles-plate").fill("00AA111");
      await ctx.page.getByTestId("fleet-vehicles-make").fill("MAN");
      await ctx.page.getByTestId("fleet-vehicles-model").fill("TGE");
      await ctx.page.getByTestId("fleet-vehicles-year").fill("2024");
      await ctx.page.getByTestId("fleet-vehicles-kind").selectOption("truck");

      const submit = ctx.page.getByTestId("fleet-vehicles-submit");
      await expect(submit).toBeEnabled();
      await submit.click();

      // The mock captured the POST — assert the body shape.
      if (postBody === null) {
        throw new Error("expected the vehicles POST mock to have captured a body");
      }
      const body: VehiclePostBody = postBody;
      expect(body.plate).toBe("00AA111");
      expect(body.make).toBe("MAN");
      expect(body.model).toBe("TGE");
      expect(body.year).toBe(2024);
      expect(body.kind).toBe("truck");
      // The route stamps an idempotency key of the form "vehicle-…"
      // via generateFleetIdempotencyKey("vehicle"). Assert the
      // prefix (the suffix is Date.now() and not deterministic).
      expect(body.idempotencyKey).toMatch(/^vehicle-/);
    } finally {
      await ctx.page.context().close();
    }
  });
});

/* ────────── Drivers POST ────────── */

test.describe("Fleet — Drivers POST", () => {
  test("filling the form + clicking submit POSTs to /api/fleet/drivers with the idempotency key", async ({
    browser,
    request,
    page,
  }) => {
    interface DriverPostBody {
      fullName: string;
      phone?: string;
      licenseNumber: string;
      idempotencyKey: string;
    }
    let postBody: DriverPostBody | null = null;
    await page.route("**/api/fleet/**", async (route) => {
      if (
        requestMatchesPath(route.request(), "/api/fleet/drivers") &&
        route.request().method() === "POST"
      ) {
        try {
          const raw = JSON.parse(route.request().postData() ?? "{}") as Partial<DriverPostBody>;
          postBody = {
            fullName: String(raw.fullName ?? ""),
            phone: typeof raw.phone === "string" ? raw.phone : undefined,
            licenseNumber: String(raw.licenseNumber ?? ""),
            idempotencyKey: String(raw.idempotencyKey ?? ""),
          };
        } catch {
          postBody = null;
        }
        route.fulfill({
          status: 200,
          contentType: "application/json",
          body: JSON.stringify({ ok: true, driver: { id: DRIVER_ID } }),
        });
        return;
      }
      installFleetApiMocks(route);
    });

    const ctx = await authedPage(browser, request);
    try {
      await ctx.page.goto("/app/fleet");
      await waitForHydration(ctx.page);

      await ctx.page.getByTestId("fleet-tab-drivers").click();
      await expect(
        ctx.page.getByTestId("fleet-drivers-form"),
      ).toBeVisible();

      await ctx.page.getByTestId("fleet-drivers-fullName").fill("Արամ Հայկականյան");
      await ctx.page.getByTestId("fleet-drivers-phone").fill("+37499000111");
      await ctx.page.getByTestId("fleet-drivers-licenseNumber").fill("AM-2026-001");

      const submit = ctx.page.getByTestId("fleet-drivers-submit");
      await expect(submit).toBeEnabled();
      await submit.click();

      if (postBody === null) {
        throw new Error("expected the drivers POST mock to have captured a body");
      }
      const body: DriverPostBody = postBody;
      expect(body.fullName).toBe("Արամ Հայկականյան");
      expect(body.phone).toBe("+37499000111");
      expect(body.licenseNumber).toBe("AM-2026-001");
      expect(body.idempotencyKey).toMatch(/^driver-/);
    } finally {
      await ctx.page.context().close();
    }
  });
});

/* ────────── Trips POST + PATCH /status ────────── */

test.describe("Fleet — Trips POST + PATCH status", () => {
  test("submitting a trip then clicking Departed POSTs + PATCHes the status envelope", async ({
    browser,
    request,
    page,
  }) => {
    interface TripPostBody {
      vehicleId: string;
      driverId: string;
      origin: string;
      destination: string;
      scheduledDeparture: string;
      idempotencyKey: string;
    }
    interface TripPatchBody {
      action: "departed" | "arrived" | "cancelled";
      idempotencyKey: string;
    }
    let postBody: TripPostBody | null = null;
    let patchBody: TripPatchBody | null = null;
    let patchPath: string | null = null;
    await page.route("**/api/fleet/**", async (route) => {
      if (
        requestMatchesPath(route.request(), "/api/fleet/trips") &&
        route.request().method() === "POST"
      ) {
        try {
          const raw = JSON.parse(route.request().postData() ?? "{}") as Partial<TripPostBody>;
          postBody = {
            vehicleId: String(raw.vehicleId ?? ""),
            driverId: String(raw.driverId ?? ""),
            origin: String(raw.origin ?? ""),
            destination: String(raw.destination ?? ""),
            scheduledDeparture: String(raw.scheduledDeparture ?? ""),
            idempotencyKey: String(raw.idempotencyKey ?? ""),
          };
        } catch {
          postBody = null;
        }
        route.fulfill({
          status: 200,
          contentType: "application/json",
          body: JSON.stringify({ ok: true, trip: { id: TRIP_ID } }),
        });
        return;
      }
      if (requestMatchesTripStatusPatch(route.request())) {
        patchPath = new URL(route.request().url()).pathname;
        try {
          const raw = JSON.parse(route.request().postData() ?? "{}") as Partial<TripPatchBody>;
          patchBody = {
            action: (raw.action ?? "departed") as TripPatchBody["action"],
            idempotencyKey: String(raw.idempotencyKey ?? ""),
          };
        } catch {
          patchBody = null;
        }
        route.fulfill({
          status: 200,
          contentType: "application/json",
          body: JSON.stringify({ ok: true, trip: { id: TRIP_ID, status: "in_transit" } }),
        });
        return;
      }
      installFleetApiMocks(route);
    });

    const ctx = await authedPage(browser, request);
    try {
      await ctx.page.goto("/app/fleet");
      await waitForHydration(ctx.page);

      await ctx.page.getByTestId("fleet-tab-trips").click();
      await expect(ctx.page.getByTestId("fleet-trips-form")).toBeVisible();

      // The trip form has 5 inputs: vehicleId, driverId, origin,
      // destination, scheduledDeparture.
      await ctx.page.getByTestId("fleet-trips-vehicleId").fill(VEHICLE_ID);
      await ctx.page.getByTestId("fleet-trips-driverId").fill(DRIVER_ID);
      await ctx.page.getByTestId("fleet-trips-origin").fill("Yerevan");
      await ctx.page.getByTestId("fleet-trips-destination").fill("Gyumri");
      await ctx.page
        .getByTestId("fleet-trips-scheduledDeparture")
        .fill("2026-06-13T08:00");

      const submit = ctx.page.getByTestId("fleet-trips-submit");
      await expect(submit).toBeEnabled();
      await submit.click();

      if (postBody === null) {
        throw new Error("expected the trips POST mock to have captured a body");
      }
      const body: TripPostBody = postBody;
      expect(body.vehicleId).toBe(VEHICLE_ID);
      expect(body.driverId).toBe(DRIVER_ID);
      expect(body.origin).toBe("Yerevan");
      expect(body.destination).toBe("Gyumri");
      expect(body.scheduledDeparture).toBe("2026-06-13T08:00");
      expect(body.idempotencyKey).toMatch(/^trip-/);

      // Click the "Departed" PATCH button on the new row. The
      // row's button only appears for status="planned" trips
      // (the route uses fleetTripStatusCanTransition to gate
      // visibility), so this is also a state-machine smoke check.
      const departed = ctx.page.getByTestId(`fleet-trip-${TRIP_ID}-departed`);
      await expect(departed).toBeVisible();
      await departed.click();

      if (patchBody === null) {
        throw new Error("expected the trips PATCH mock to have captured a body");
      }
      const patchBodyTyped: TripPatchBody = patchBody;
      expect(patchPath).toBe(`/api/fleet/trips/${TRIP_ID}/status`);
      expect(patchBodyTyped.action).toBe("departed");
      expect(patchBodyTyped.idempotencyKey).toMatch(/^trip-status-/);
    } finally {
      await ctx.page.context().close();
    }
  });
});

/* ────────── Fuel POST + efficiency GET ────────── */

test.describe("Fleet — Fuel POST + efficiency analytics", () => {
  test("submitting a fuel log + the efficiency rollup table renders", async ({
    browser,
    request,
    page,
  }) => {
    interface FuelPostBody {
      vehicleId: string;
      liters: number;
      odometerKm: number;
      fuelCostPerL: number;
      idempotencyKey: string;
    }
    let postBody: FuelPostBody | null = null;
    await page.route("**/api/fleet/**", async (route) => {
      if (
        requestMatchesPath(route.request(), "/api/fleet/fuel-logs") &&
        route.request().method() === "POST"
      ) {
        try {
          const raw = JSON.parse(route.request().postData() ?? "{}") as Partial<FuelPostBody>;
          postBody = {
            vehicleId: String(raw.vehicleId ?? ""),
            liters: typeof raw.liters === "number" ? raw.liters : 0,
            odometerKm: typeof raw.odometerKm === "number" ? raw.odometerKm : 0,
            fuelCostPerL:
              typeof raw.fuelCostPerL === "number" ? raw.fuelCostPerL : 0,
            idempotencyKey: String(raw.idempotencyKey ?? ""),
          };
        } catch {
          postBody = null;
        }
        route.fulfill({
          status: 200,
          contentType: "application/json",
          body: JSON.stringify({ ok: true, log: { id: FUEL_ID } }),
        });
        return;
      }
      // Override the analytics GET to a stable shape so the
      // efficiency table renders without depending on the
      // live SQL aggregation.
      if (requestMatchesPath(
        route.request(),
        "/api/fleet/analytics/fuel-efficiency",
      )) {
        route.fulfill({
          status: 200,
          contentType: "application/json",
          body: JSON.stringify({
            ok: true,
            efficiency: [
              { vehicleId: VEHICLE_ID, liters: 120, km: 1500, lPer100km: 8, kmPerL: 12.5 },
            ],
          }),
        });
        return;
      }
      installFleetApiMocks(route);
    });

    const ctx = await authedPage(browser, request);
    try {
      await ctx.page.goto("/app/fleet");
      await waitForHydration(ctx.page);

      await ctx.page.getByTestId("fleet-tab-fuel").click();
      await expect(ctx.page.getByTestId("fleet-fuel-form")).toBeVisible();

      await ctx.page.getByTestId("fleet-fuel-vehicleId").fill(VEHICLE_ID);
      await ctx.page.getByTestId("fleet-fuel-liters").fill("60.5");
      await ctx.page.getByTestId("fleet-fuel-odometerKm").fill("75000");
      await ctx.page.getByTestId("fleet-fuel-fuelCostPerL").fill("510");

      const submit = ctx.page.getByTestId("fleet-fuel-submit");
      await expect(submit).toBeEnabled();
      await submit.click();

      if (postBody === null) {
        throw new Error("expected the fuel POST mock to have captured a body");
      }
      const body: FuelPostBody = postBody;
      expect(body.vehicleId).toBe(VEHICLE_ID);
      expect(body.liters).toBe(60.5);
      expect(body.odometerKm).toBe(75000);
      expect(body.fuelCostPerL).toBe(510);
      expect(body.idempotencyKey).toMatch(/^fuel-/);

      // The efficiency rollup table renders the {vehicleId,
      // lPer100km} rows from the analytics GET.
      const effTable = ctx.page.getByTestId("fleet-fuel-efficiency-table");
      await expect(effTable).toBeVisible();
      const rows = effTable.locator("[data-testid='fleet-fuel-efficiency-row']");
      await expect(rows).toHaveCount(1);
      await expect(rows.nth(0)).toContainText(VEHICLE_ID);
      await expect(rows.nth(0)).toContainText("8");
    } finally {
      await ctx.page.context().close();
    }
  });
});

/* ────────── Repairs POST + backlog analytics ────────── */

test.describe("Fleet — Repairs POST + maintenance-backlog analytics", () => {
  test("submitting a repair + the backlog rollup table renders", async ({
    browser,
    request,
    page,
  }) => {
    interface RepairPostBody {
      vehicleId: string;
      kind: string;
      odometerKm: number;
      cost: number;
      nextDueAt?: string;
      idempotencyKey: string;
    }
    let postBody: RepairPostBody | null = null;
    await page.route("**/api/fleet/**", async (route) => {
      if (
        requestMatchesPath(route.request(), "/api/fleet/repairs") &&
        route.request().method() === "POST"
      ) {
        try {
          const raw = JSON.parse(route.request().postData() ?? "{}") as Partial<RepairPostBody>;
          postBody = {
            vehicleId: String(raw.vehicleId ?? ""),
            kind: String(raw.kind ?? ""),
            odometerKm: typeof raw.odometerKm === "number" ? raw.odometerKm : 0,
            cost: typeof raw.cost === "number" ? raw.cost : 0,
            nextDueAt:
              typeof raw.nextDueAt === "string" ? raw.nextDueAt : undefined,
            idempotencyKey: String(raw.idempotencyKey ?? ""),
          };
        } catch {
          postBody = null;
        }
        route.fulfill({
          status: 200,
          contentType: "application/json",
          body: JSON.stringify({ ok: true, repair: { id: REPAIR_ID } }),
        });
        return;
      }
      // Override the backlog GET to a stable shape.
      if (requestMatchesPath(
        route.request(),
        "/api/fleet/analytics/maintenance-backlog",
      )) {
        route.fulfill({
          status: 200,
          contentType: "application/json",
          body: JSON.stringify({
            ok: true,
            backlog: [
              { vehicleId: VEHICLE_ID, kind: "oil-change", overdueDays: 14 },
            ],
          }),
        });
        return;
      }
      installFleetApiMocks(route);
    });

    const ctx = await authedPage(browser, request);
    try {
      await ctx.page.goto("/app/fleet");
      await waitForHydration(ctx.page);

      await ctx.page.getByTestId("fleet-tab-repairs").click();
      await expect(ctx.page.getByTestId("fleet-repairs-form")).toBeVisible();

      await ctx.page.getByTestId("fleet-repairs-vehicleId").fill(VEHICLE_ID);
      await ctx.page.getByTestId("fleet-repairs-kind").selectOption("oil-change");
      await ctx.page.getByTestId("fleet-repairs-odometerKm").fill("75500");
      await ctx.page.getByTestId("fleet-repairs-cost").fill("45000");
      await ctx.page.getByTestId("fleet-repairs-nextDueAt").fill("2026-09-01");

      const submit = ctx.page.getByTestId("fleet-repairs-submit");
      await expect(submit).toBeEnabled();
      await submit.click();

      if (postBody === null) {
        throw new Error("expected the repairs POST mock to have captured a body");
      }
      const body: RepairPostBody = postBody;
      expect(body.vehicleId).toBe(VEHICLE_ID);
      expect(body.kind).toBe("oil-change");
      expect(body.odometerKm).toBe(75500);
      expect(body.cost).toBe(45000);
      expect(body.nextDueAt).toBe("2026-09-01");
      expect(body.idempotencyKey).toMatch(/^repair-/);

      // The backlog rollup table renders the {vehicleId, kind,
      // overdueDays} rows from the analytics GET.
      const backlog = ctx.page.getByTestId("fleet-repairs-backlog-table");
      await expect(backlog).toBeVisible();
      const rows = backlog.locator("[data-testid='fleet-repairs-backlog-row']");
      await expect(rows).toHaveCount(1);
      await expect(rows.nth(0)).toContainText(VEHICLE_ID);
      await expect(rows.nth(0)).toContainText("oil-change");
      await expect(rows.nth(0)).toContainText("14");
    } finally {
      await ctx.page.context().close();
    }
  });
});

/* ────────── Tires POST ────────── */

test.describe("Fleet — Tires POST", () => {
  test("filling the form + clicking submit POSTs to /api/fleet/tires/install with the idempotency key", async ({
    browser,
    request,
    page,
  }) => {
    interface TirePostBody {
      vehicleId: string;
      position: string;
      brand?: string;
      installedAt: string;
      odometerAtInstall?: number;
      expectedLifeKm?: number;
      idempotencyKey: string;
    }
    let postBody: TirePostBody | null = null;
    let postPath: string | null = null;
    await page.route("**/api/fleet/**", async (route) => {
      if (requestMatchesPath(route.request(), "/api/fleet/tires/install")) {
        postPath = new URL(route.request().url()).pathname;
        try {
          const raw = JSON.parse(route.request().postData() ?? "{}") as Partial<TirePostBody>;
          postBody = {
            vehicleId: String(raw.vehicleId ?? ""),
            position: String(raw.position ?? ""),
            brand: typeof raw.brand === "string" ? raw.brand : undefined,
            installedAt: String(raw.installedAt ?? ""),
            odometerAtInstall:
              typeof raw.odometerAtInstall === "number"
                ? raw.odometerAtInstall
                : undefined,
            expectedLifeKm:
              typeof raw.expectedLifeKm === "number"
                ? raw.expectedLifeKm
                : undefined,
            idempotencyKey: String(raw.idempotencyKey ?? ""),
          };
        } catch {
          postBody = null;
        }
        route.fulfill({
          status: 200,
          contentType: "application/json",
          body: JSON.stringify({ ok: true, tire: { id: TIRE_ID } }),
        });
        return;
      }
      installFleetApiMocks(route);
    });

    const ctx = await authedPage(browser, request);
    try {
      await ctx.page.goto("/app/fleet");
      await waitForHydration(ctx.page);

      await ctx.page.getByTestId("fleet-tab-tires").click();
      await expect(ctx.page.getByTestId("fleet-tires-form")).toBeVisible();

      await ctx.page.getByTestId("fleet-tires-vehicleId").fill(VEHICLE_ID);
      await ctx.page.getByTestId("fleet-tires-position").selectOption("front-left");
      await ctx.page.getByTestId("fleet-tires-brand").fill("Michelin");
      await ctx.page.getByTestId("fleet-tires-installedAt").fill("2026-06-01");
      await ctx.page.getByTestId("fleet-tires-odometerAtInstall").fill("75000");
      await ctx.page.getByTestId("fleet-tires-expectedLifeKm").fill("60000");

      const submit = ctx.page.getByTestId("fleet-tires-submit");
      await expect(submit).toBeEnabled();
      await submit.click();

      expect(postPath).toBe("/api/fleet/tires/install");
      if (postBody === null) {
        throw new Error("expected the tires POST mock to have captured a body");
      }
      const body: TirePostBody = postBody;
      expect(body.vehicleId).toBe(VEHICLE_ID);
      expect(body.position).toBe("front-left");
      expect(body.brand).toBe("Michelin");
      expect(body.installedAt).toBe("2026-06-01");
      expect(body.odometerAtInstall).toBe(75000);
      expect(body.expectedLifeKm).toBe(60000);
      expect(body.idempotencyKey).toMatch(/^tire-/);
    } finally {
      await ctx.page.context().close();
    }
  });
});

/* ────────── ColdChain compliance GET ────────── */

test.describe("Fleet — ColdChain compliance GET", () => {
  test("selecting vehicle + category + clicking compute GETs the compliance report and the breaches table renders", async ({
    browser,
    request,
    page,
  }) => {
    let compliancePath: string | null = null;
    let complianceCategory: string | null = null;
    await page.route("**/api/fleet/**", async (route) => {
      if (requestMatchesColdChainCompliance(route.request())) {
        const url = new URL(route.request().url());
        compliancePath = url.pathname;
        complianceCategory = url.searchParams.get("category");
        route.fulfill({
          status: 200,
          contentType: "application/json",
          body: JSON.stringify({
            ok: true,
            category: "dairy",
            report: {
              worstTempC: 6.4,
              sustainedMinutes: 28,
              breaches: [
                {
                  startedAt: "2026-06-12T08:14:00Z",
                  endedAt: "2026-06-12T08:42:00Z",
                  minutes: 28,
                },
              ],
            },
          }),
        });
        return;
      }
      installFleetApiMocks(route);
    });

    const ctx = await authedPage(browser, request);
    try {
      await ctx.page.goto("/app/fleet");
      await waitForHydration(ctx.page);

      await ctx.page.getByTestId("fleet-tab-coldchain").click();
      await expect(
        ctx.page.getByTestId("fleet-coldchain-form"),
      ).toBeVisible();

      // The cold-chain form has vehicleId + category selects
      // + a "Compute compliance" button. There's no
      // free-form submit; the route fires the GET on click.
      await ctx.page
        .getByTestId("fleet-coldchain-vehicleId")
        .selectOption(VEHICLE_ID);
      await ctx.page
        .getByTestId("fleet-coldchain-category")
        .selectOption("dairy");

      const compute = ctx.page.getByTestId("fleet-coldchain-submit");
      await expect(compute).toBeEnabled();
      await compute.click();

      // The mock captured the GET — assert the path + query.
      expect(compliancePath).toBe(
        `/api/fleet/vehicles/${VEHICLE_ID}/cold-chain-compliance`,
      );
      expect(complianceCategory).toBe("dairy");

      // The breaches table renders the {startedAt, endedAt,
      // minutes} rows from the compliance report.
      const breaches = ctx.page.getByTestId("fleet-coldchain-breaches-table");
      await expect(breaches).toBeVisible();
      const rows = breaches.locator(
        "[data-testid='fleet-coldchain-breach-row']",
      );
      await expect(rows).toHaveCount(1);
      await expect(rows.nth(0)).toContainText("28");
    } finally {
      await ctx.page.context().close();
    }
  });
});

/* ────────── 403 access gate ────────── */

test.describe("Fleet — 403 access gate", () => {
  test("does not render the 403 card for a default authenticated user", async ({
    browser,
    request,
    page,
  }) => {
    // The 403 path is a no-op for the live route today: the
    // workspace does not yet read a `userAccess` from the
    // session (the plan says: "Server enforces; UI defaults
    // to permissive until the auth context is wired in 8.4").
    // The route exports a FleetAccessDeniedCard component,
    // but the live workspace is unconditional. This spec is
    // a regression guard — if a future change wires the
    // workspace to read a role from the session and defaults
    // it to "none" for unprivileged users, this test will
    // fail loudly.
    await page.route("**/api/fleet/**", installFleetApiMocks);

    const ctx = await authedPage(browser, request);
    try {
      await ctx.page.goto("/app/fleet");
      await waitForHydration(ctx.page);

      // The 403 card must NOT be present for a default session.
      await expect(ctx.page.getByTestId("fleet-403")).toHaveCount(0);
      // The tab strip + the vehicles form MUST be present —
      // the workspace is the default render, the 403 is opt-in.
      await expect(
        ctx.page.getByTestId("fleet-tab-vehicles"),
      ).toBeVisible();
      await expect(
        ctx.page.getByTestId("fleet-vehicles-form"),
      ).toBeVisible();
    } finally {
      await ctx.page.context().close();
    }
  });
});
