/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as LoginMfaRouteImport } from './routes/login.mfa'
import { Route as AppCopilotRouteImport } from './routes/app/copilot'
import { Route as AppAppIdRouteImport } from './routes/app/$appId'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AppPurchaseIndexRouteImport } from './routes/app/purchase/index'
import { Route as AppProjectsIndexRouteImport } from './routes/app/projects/index'
import { Route as AppPeopleIndexRouteImport } from './routes/app/people/index'
import { Route as AppInventoryIndexRouteImport } from './routes/app/inventory/index'
import { Route as AppDocsIndexRouteImport } from './routes/app/docs/index'
import { Route as AppDeskIndexRouteImport } from './routes/app/desk/index'
import { Route as AppCrmIndexRouteImport } from './routes/app/crm/index'
import { Route as AppCfoIndexRouteImport } from './routes/app/cfo/index'
import { Route as AppAnalyticsIndexRouteImport } from './routes/app/analytics/index'
import { Route as AppPurchaseOrderIdRouteImport } from './routes/app/purchase/$orderId'
import { Route as AppProjectsProjectIdRouteImport } from './routes/app/projects/$projectId'
import { Route as AppPeopleEmployeeIdRouteImport } from './routes/app/people/$employeeId'
import { Route as AppInventoryItemIdRouteImport } from './routes/app/inventory/$itemId'
import { Route as AppDocsDocumentIdRouteImport } from './routes/app/docs/$documentId'
import { Route as AppDeskCaseIdRouteImport } from './routes/app/desk/$caseId'
import { Route as AppCrmQuoteIdRouteImport } from './routes/app/crm/$quoteId'
import { Route as AppCfoLoanIdRouteImport } from './routes/app/cfo/$loanId'
import { Route as AppAnalyticsMetricIdRouteImport } from './routes/app/analytics/$metricId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const LoginMfaRoute = LoginMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => LoginRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAppIdRoute = AppAppIdRouteImport.update({
  id: '/$appId',
  path: '/$appId',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPurchaseIndexRoute = AppPurchaseIndexRouteImport.update({
  id: '/purchase/',
  path: '/purchase/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPeopleIndexRoute = AppPeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocsIndexRoute = AppDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDeskIndexRoute = AppDeskIndexRouteImport.update({
  id: '/desk/',
  path: '/desk/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCrmIndexRoute = AppCrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCfoIndexRoute = AppCfoIndexRouteImport.update({
  id: '/cfo/',
  path: '/cfo/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAnalyticsIndexRoute = AppAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPurchaseOrderIdRoute = AppPurchaseOrderIdRouteImport.update({
  id: '/purchase/$orderId',
  path: '/purchase/$orderId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPeopleEmployeeIdRoute = AppPeopleEmployeeIdRouteImport.update({
  id: '/people/$employeeId',
  path: '/people/$employeeId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventoryItemIdRoute = AppInventoryItemIdRouteImport.update({
  id: '/inventory/$itemId',
  path: '/inventory/$itemId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocsDocumentIdRoute = AppDocsDocumentIdRouteImport.update({
  id: '/docs/$documentId',
  path: '/docs/$documentId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDeskCaseIdRoute = AppDeskCaseIdRouteImport.update({
  id: '/desk/$caseId',
  path: '/desk/$caseId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCrmQuoteIdRoute = AppCrmQuoteIdRouteImport.update({
  id: '/crm/$quoteId',
  path: '/crm/$quoteId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCfoLoanIdRoute = AppCfoLoanIdRouteImport.update({
  id: '/cfo/$loanId',
  path: '/cfo/$loanId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAnalyticsMetricIdRoute = AppAnalyticsMetricIdRouteImport.update({
  id: '/analytics/$metricId',
  path: '/analytics/$metricId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/app/$appId': typeof AppAppIdRoute
  '/app/copilot': typeof AppCopilotRoute
  '/login/mfa': typeof LoginMfaRoute
  '/app/': typeof AppIndexRoute
  '/app/analytics/$metricId': typeof AppAnalyticsMetricIdRoute
  '/app/cfo/$loanId': typeof AppCfoLoanIdRoute
  '/app/crm/$quoteId': typeof AppCrmQuoteIdRoute
  '/app/desk/$caseId': typeof AppDeskCaseIdRoute
  '/app/docs/$documentId': typeof AppDocsDocumentIdRoute
  '/app/inventory/$itemId': typeof AppInventoryItemIdRoute
  '/app/people/$employeeId': typeof AppPeopleEmployeeIdRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/purchase/$orderId': typeof AppPurchaseOrderIdRoute
  '/app/analytics/': typeof AppAnalyticsIndexRoute
  '/app/cfo/': typeof AppCfoIndexRoute
  '/app/crm/': typeof AppCrmIndexRoute
  '/app/desk/': typeof AppDeskIndexRoute
  '/app/docs/': typeof AppDocsIndexRoute
  '/app/inventory/': typeof AppInventoryIndexRoute
  '/app/people/': typeof AppPeopleIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/purchase/': typeof AppPurchaseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/app/$appId': typeof AppAppIdRoute
  '/app/copilot': typeof AppCopilotRoute
  '/login/mfa': typeof LoginMfaRoute
  '/app': typeof AppIndexRoute
  '/app/analytics/$metricId': typeof AppAnalyticsMetricIdRoute
  '/app/cfo/$loanId': typeof AppCfoLoanIdRoute
  '/app/crm/$quoteId': typeof AppCrmQuoteIdRoute
  '/app/desk/$caseId': typeof AppDeskCaseIdRoute
  '/app/docs/$documentId': typeof AppDocsDocumentIdRoute
  '/app/inventory/$itemId': typeof AppInventoryItemIdRoute
  '/app/people/$employeeId': typeof AppPeopleEmployeeIdRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/purchase/$orderId': typeof AppPurchaseOrderIdRoute
  '/app/analytics': typeof AppAnalyticsIndexRoute
  '/app/cfo': typeof AppCfoIndexRoute
  '/app/crm': typeof AppCrmIndexRoute
  '/app/desk': typeof AppDeskIndexRoute
  '/app/docs': typeof AppDocsIndexRoute
  '/app/inventory': typeof AppInventoryIndexRoute
  '/app/people': typeof AppPeopleIndexRoute
  '/app/projects': typeof AppProjectsIndexRoute
  '/app/purchase': typeof AppPurchaseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/app/$appId': typeof AppAppIdRoute
  '/app/copilot': typeof AppCopilotRoute
  '/login/mfa': typeof LoginMfaRoute
  '/app/': typeof AppIndexRoute
  '/app/analytics/$metricId': typeof AppAnalyticsMetricIdRoute
  '/app/cfo/$loanId': typeof AppCfoLoanIdRoute
  '/app/crm/$quoteId': typeof AppCrmQuoteIdRoute
  '/app/desk/$caseId': typeof AppDeskCaseIdRoute
  '/app/docs/$documentId': typeof AppDocsDocumentIdRoute
  '/app/inventory/$itemId': typeof AppInventoryItemIdRoute
  '/app/people/$employeeId': typeof AppPeopleEmployeeIdRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/purchase/$orderId': typeof AppPurchaseOrderIdRoute
  '/app/analytics/': typeof AppAnalyticsIndexRoute
  '/app/cfo/': typeof AppCfoIndexRoute
  '/app/crm/': typeof AppCrmIndexRoute
  '/app/desk/': typeof AppDeskIndexRoute
  '/app/docs/': typeof AppDocsIndexRoute
  '/app/inventory/': typeof AppInventoryIndexRoute
  '/app/people/': typeof AppPeopleIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/purchase/': typeof AppPurchaseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/api/$'
    | '/app/$appId'
    | '/app/copilot'
    | '/login/mfa'
    | '/app/'
    | '/app/analytics/$metricId'
    | '/app/cfo/$loanId'
    | '/app/crm/$quoteId'
    | '/app/desk/$caseId'
    | '/app/docs/$documentId'
    | '/app/inventory/$itemId'
    | '/app/people/$employeeId'
    | '/app/projects/$projectId'
    | '/app/purchase/$orderId'
    | '/app/analytics/'
    | '/app/cfo/'
    | '/app/crm/'
    | '/app/desk/'
    | '/app/docs/'
    | '/app/inventory/'
    | '/app/people/'
    | '/app/projects/'
    | '/app/purchase/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/$'
    | '/app/$appId'
    | '/app/copilot'
    | '/login/mfa'
    | '/app'
    | '/app/analytics/$metricId'
    | '/app/cfo/$loanId'
    | '/app/crm/$quoteId'
    | '/app/desk/$caseId'
    | '/app/docs/$documentId'
    | '/app/inventory/$itemId'
    | '/app/people/$employeeId'
    | '/app/projects/$projectId'
    | '/app/purchase/$orderId'
    | '/app/analytics'
    | '/app/cfo'
    | '/app/crm'
    | '/app/desk'
    | '/app/docs'
    | '/app/inventory'
    | '/app/people'
    | '/app/projects'
    | '/app/purchase'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/api/$'
    | '/app/$appId'
    | '/app/copilot'
    | '/login/mfa'
    | '/app/'
    | '/app/analytics/$metricId'
    | '/app/cfo/$loanId'
    | '/app/crm/$quoteId'
    | '/app/desk/$caseId'
    | '/app/docs/$documentId'
    | '/app/inventory/$itemId'
    | '/app/people/$employeeId'
    | '/app/projects/$projectId'
    | '/app/purchase/$orderId'
    | '/app/analytics/'
    | '/app/cfo/'
    | '/app/crm/'
    | '/app/desk/'
    | '/app/docs/'
    | '/app/inventory/'
    | '/app/people/'
    | '/app/projects/'
    | '/app/purchase/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/login/mfa': {
      id: '/login/mfa'
      path: '/mfa'
      fullPath: '/login/mfa'
      preLoaderRoute: typeof LoginMfaRouteImport
      parentRoute: typeof LoginRoute
    }
    '/app/copilot': {
      id: '/app/copilot'
      path: '/copilot'
      fullPath: '/app/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$appId': {
      id: '/app/$appId'
      path: '/$appId'
      fullPath: '/app/$appId'
      preLoaderRoute: typeof AppAppIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/purchase/': {
      id: '/app/purchase/'
      path: '/purchase'
      fullPath: '/app/purchase/'
      preLoaderRoute: typeof AppPurchaseIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/people/': {
      id: '/app/people/'
      path: '/people'
      fullPath: '/app/people/'
      preLoaderRoute: typeof AppPeopleIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/inventory/': {
      id: '/app/inventory/'
      path: '/inventory'
      fullPath: '/app/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/docs/': {
      id: '/app/docs/'
      path: '/docs'
      fullPath: '/app/docs/'
      preLoaderRoute: typeof AppDocsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/desk/': {
      id: '/app/desk/'
      path: '/desk'
      fullPath: '/app/desk/'
      preLoaderRoute: typeof AppDeskIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/crm/': {
      id: '/app/crm/'
      path: '/crm'
      fullPath: '/app/crm/'
      preLoaderRoute: typeof AppCrmIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/cfo/': {
      id: '/app/cfo/'
      path: '/cfo'
      fullPath: '/app/cfo/'
      preLoaderRoute: typeof AppCfoIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/analytics/': {
      id: '/app/analytics/'
      path: '/analytics'
      fullPath: '/app/analytics/'
      preLoaderRoute: typeof AppAnalyticsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/purchase/$orderId': {
      id: '/app/purchase/$orderId'
      path: '/purchase/$orderId'
      fullPath: '/app/purchase/$orderId'
      preLoaderRoute: typeof AppPurchaseOrderIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/people/$employeeId': {
      id: '/app/people/$employeeId'
      path: '/people/$employeeId'
      fullPath: '/app/people/$employeeId'
      preLoaderRoute: typeof AppPeopleEmployeeIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/inventory/$itemId': {
      id: '/app/inventory/$itemId'
      path: '/inventory/$itemId'
      fullPath: '/app/inventory/$itemId'
      preLoaderRoute: typeof AppInventoryItemIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/docs/$documentId': {
      id: '/app/docs/$documentId'
      path: '/docs/$documentId'
      fullPath: '/app/docs/$documentId'
      preLoaderRoute: typeof AppDocsDocumentIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/desk/$caseId': {
      id: '/app/desk/$caseId'
      path: '/desk/$caseId'
      fullPath: '/app/desk/$caseId'
      preLoaderRoute: typeof AppDeskCaseIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/crm/$quoteId': {
      id: '/app/crm/$quoteId'
      path: '/crm/$quoteId'
      fullPath: '/app/crm/$quoteId'
      preLoaderRoute: typeof AppCrmQuoteIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/cfo/$loanId': {
      id: '/app/cfo/$loanId'
      path: '/cfo/$loanId'
      fullPath: '/app/cfo/$loanId'
      preLoaderRoute: typeof AppCfoLoanIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/analytics/$metricId': {
      id: '/app/analytics/$metricId'
      path: '/analytics/$metricId'
      fullPath: '/app/analytics/$metricId'
      preLoaderRoute: typeof AppAnalyticsMetricIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAppIdRoute: typeof AppAppIdRoute
  AppCopilotRoute: typeof AppCopilotRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAnalyticsMetricIdRoute: typeof AppAnalyticsMetricIdRoute
  AppCfoLoanIdRoute: typeof AppCfoLoanIdRoute
  AppCrmQuoteIdRoute: typeof AppCrmQuoteIdRoute
  AppDeskCaseIdRoute: typeof AppDeskCaseIdRoute
  AppDocsDocumentIdRoute: typeof AppDocsDocumentIdRoute
  AppInventoryItemIdRoute: typeof AppInventoryItemIdRoute
  AppPeopleEmployeeIdRoute: typeof AppPeopleEmployeeIdRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppPurchaseOrderIdRoute: typeof AppPurchaseOrderIdRoute
  AppAnalyticsIndexRoute: typeof AppAnalyticsIndexRoute
  AppCfoIndexRoute: typeof AppCfoIndexRoute
  AppCrmIndexRoute: typeof AppCrmIndexRoute
  AppDeskIndexRoute: typeof AppDeskIndexRoute
  AppDocsIndexRoute: typeof AppDocsIndexRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
  AppPeopleIndexRoute: typeof AppPeopleIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppPurchaseIndexRoute: typeof AppPurchaseIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAppIdRoute: AppAppIdRoute,
  AppCopilotRoute: AppCopilotRoute,
  AppIndexRoute: AppIndexRoute,
  AppAnalyticsMetricIdRoute: AppAnalyticsMetricIdRoute,
  AppCfoLoanIdRoute: AppCfoLoanIdRoute,
  AppCrmQuoteIdRoute: AppCrmQuoteIdRoute,
  AppDeskCaseIdRoute: AppDeskCaseIdRoute,
  AppDocsDocumentIdRoute: AppDocsDocumentIdRoute,
  AppInventoryItemIdRoute: AppInventoryItemIdRoute,
  AppPeopleEmployeeIdRoute: AppPeopleEmployeeIdRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppPurchaseOrderIdRoute: AppPurchaseOrderIdRoute,
  AppAnalyticsIndexRoute: AppAnalyticsIndexRoute,
  AppCfoIndexRoute: AppCfoIndexRoute,
  AppCrmIndexRoute: AppCrmIndexRoute,
  AppDeskIndexRoute: AppDeskIndexRoute,
  AppDocsIndexRoute: AppDocsIndexRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
  AppPeopleIndexRoute: AppPeopleIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppPurchaseIndexRoute: AppPurchaseIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface LoginRouteChildren {
  LoginMfaRoute: typeof LoginMfaRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginMfaRoute: LoginMfaRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
